# Generated by Django 4.1.6 on 2023-02-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('direction', models.CharField(max_length=255, verbose_name='Direction')),
                ('level', models.CharField(max_length=255, verbose_name='Level')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('skills', models.CharField(max_length=255, verbose_name='Skills')),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=255, verbose_name='City or Remote')),
            ],
        ),
    ]
